### ISSUE TITLE
怎么访问dashboard呢？ 还是CLI方式配置节点规则等？

### ISSUE THREAD

**Issue by matthuo333** [YouYII/docker_global_transparent_proxy#1]
如题

**Comment by Yi-Z0** [comment]
可以使用 http://yacd.haishan.me ,输入对应的ip 以及端口号即可

**Comment by matthuo333** [comment]
> 可以使用 http://yacd.haishan.me ,输入对应的ip 以及端口号即可

嗯通过docker 建立成功了。想设置为dhcp，是在clash容器哪里修改呢？

**Comment by Yi-Z0** [comment]
这个是透明代理, 你只需要在需要代理的设备上设置该docker 的ip为路由ip即可
如果你想自动设置, 可能需要你的路由器支持
